name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install, build, and Test
        run: |
          yarn
          yarn build
          yarn test

      - name: Upload test coverage to codeclimate
        uses: paambaati/codeclimate-action@v2.7.2
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test:coverage
          coverageLocations: ${{github.workspace}}/test_reports/coverage/lcov.info:lcov